name = "joyrl-visitor-stats"
main = "src/index.mjs"
compatibility_date = "2026-04-20"

[vars]
ALLOWED_ORIGINS = "https://datawhalechina.github.io,http://localhost:3000"
TIMEZONE = "Asia/Shanghai"
SITE_ID = "joyrl-book"
COUNTER_SHARDS = "64"

[[kv_namespaces]]
binding = "VISITOR_STATS"
id = "068624fa667441f9b0faf39bfa53df03"
